controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

      ros__parameters:
        use_sim_time: true

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
